/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as TransformationRouteImport } from './routes/transformation'
import { Route as SleepWaterRouteImport } from './routes/sleep-water'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as GamificationRouteImport } from './routes/gamification'
import { Route as BodyMetricsRouteImport } from './routes/body-metrics'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformationRoute = TransformationRouteImport.update({
  id: '/transformation',
  path: '/transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepWaterRoute = SleepWaterRouteImport.update({
  id: '/sleep-water',
  path: '/sleep-water',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationRoute = GamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyMetricsRoute = BodyMetricsRouteImport.update({
  id: '/body-metrics',
  path: '/body-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body-metrics': typeof BodyMetricsRoute
  '/gamification': typeof GamificationRoute
  '/habits': typeof HabitsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleep-water': typeof SleepWaterRoute
  '/transformation': typeof TransformationRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body-metrics': typeof BodyMetricsRoute
  '/gamification': typeof GamificationRoute
  '/habits': typeof HabitsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleep-water': typeof SleepWaterRoute
  '/transformation': typeof TransformationRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body-metrics': typeof BodyMetricsRoute
  '/gamification': typeof GamificationRoute
  '/habits': typeof HabitsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sleep-water': typeof SleepWaterRoute
  '/transformation': typeof TransformationRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body-metrics'
    | '/gamification'
    | '/habits'
    | '/nutrition'
    | '/photos'
    | '/sitemap.xml'
    | '/sleep-water'
    | '/transformation'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body-metrics'
    | '/gamification'
    | '/habits'
    | '/nutrition'
    | '/photos'
    | '/sitemap.xml'
    | '/sleep-water'
    | '/transformation'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/body-metrics'
    | '/gamification'
    | '/habits'
    | '/nutrition'
    | '/photos'
    | '/sitemap.xml'
    | '/sleep-water'
    | '/transformation'
    | '/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyMetricsRoute: typeof BodyMetricsRoute
  GamificationRoute: typeof GamificationRoute
  HabitsRoute: typeof HabitsRoute
  NutritionRoute: typeof NutritionRoute
  PhotosRoute: typeof PhotosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SleepWaterRoute: typeof SleepWaterRoute
  TransformationRoute: typeof TransformationRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transformation': {
      id: '/transformation'
      path: '/transformation'
      fullPath: '/transformation'
      preLoaderRoute: typeof TransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep-water': {
      id: '/sleep-water'
      path: '/sleep-water'
      fullPath: '/sleep-water'
      preLoaderRoute: typeof SleepWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification': {
      id: '/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof GamificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-metrics': {
      id: '/body-metrics'
      path: '/body-metrics'
      fullPath: '/body-metrics'
      preLoaderRoute: typeof BodyMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyMetricsRoute: BodyMetricsRoute,
  GamificationRoute: GamificationRoute,
  HabitsRoute: HabitsRoute,
  NutritionRoute: NutritionRoute,
  PhotosRoute: PhotosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SleepWaterRoute: SleepWaterRoute,
  TransformationRoute: TransformationRoute,
  WorkoutsRoute: WorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
